on:
  push:

env:
  IMAGE: ghcr.io/${{ github.repository }}:latest

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create a Dockerfile
        run: |
          echo 'FROM alpine' > Dockerfile
          echo 'ENTRYPOINT ["echo", "Hello from ${{ github.repository }}!"]' >> Dockerfile

      - name: Build image
        run: docker build . -t ${{ env.IMAGE }}

      - name: Login to ghcr.io
        run: docker login https://ghcr.io -u token --password-stdin <<< ${{ secrets.READ_AND_WRITE_PACKAGES_TOKEN }}

      - name: Publish image
        run: docker push ${{ env.IMAGE }}

      - run: gh api repos/${{ github.repository_owner }}/ghcr-install/dispatches <<< '{"event_type":"build"}' --input -
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
